# Site settings
title: Vineet Bhatawadekar
author: Vineet Bhatawadekar
description: ""
url: vineet.online
baseurl: ""

# Build settings
port: 4000
exclude: [ "node_modules", "package.json", "*.log", "scripts", "src", "README.md", "LICENSE" ]

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Blog settings
permalink: /:year/:month/:title/

# Defaults for post layouts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      type: "post"

# generate sitemap
#plugins:
#  - jekyll-sitemap
